parameters:
	epoch_rating: [400]
	epoch_explanation: [300]
	beta: [0.0001]
	lambda_l2: [0.0001]
	lambda_keyphrase: [1.0]
	labmda_latent: [1.0]
	lambda_rating: [1.0]
	optimizer: [Adam]
	learning_rate: [0.0001]
	topK: [5, 10, 15, 20, 50]
	metric: [R-Precision, NDCG, Precision, Recall, MAP]
