parameters:
    models: S-E-CDE-VAE
    epoch_rating: [BEST]
    epoch_explanation: [300,400,500,600,700,800]
    beta: [BEST]
    lambda_l2: [BEST]
    lambda_keyphrase: [1.0]
    lambda_latent: [2.0, 1.0, 0.5, 0.3, 0.1, 0.01, 0.001]
    lambda_rating: [1.0]
    rank: [100]
    corruption: [0.2]
    optimizer: [Adam]
    learning_rate: [0.0001, 0.0005]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
