parameters:
    models: S-E-CDE-VAE
    epoch_rating: [400]
    epoch_explanation: [600]
    beta: [0.0001]
    lambda_l2: [0.0001]
    lambda_keyphrase: [1.0]
    labmda_latent: [0.5]
    lambda_rating: [1.0]
    optimizer: [Adam]
    learning_rate: [0.0001]
    corruption: [0.4]
    topK: [5, 10, 15, 20, 50]
    rank: [200]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
