parameters:
    models: CDE-VAE
    epoch: [300]
    lambda: [0.00001, 0.0001, 0.001, 0.01, 0.1]
    rank: [200]
    corruption: [0.2]
    optimizer: [Adam]
    learning_rate: [0.0001, 0.0005, 0.001]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
