parameters:
    models: CDE-VAE
    epoch: [1, 2]
    lambda: [80.0]
    rank: [200]
    corruption: [0.5]
    optimizer: [RMSProp]
    learning_rate: [0.0001]
    topK: [5, 10, 15, 20, 50]
    metric: [R-Precision, NDCG, Precision, Recall, MAP]
